config/routes.rb
Media::Application.routes.draw do
  
  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'partners' => 'pages#partners'
  get 'services' => 'pages#services'
  get 'contact' => 'pages#contact'
  get 'events1' => 'pages#events1'
  get 'events2' => 'pages#events2'
  get 'events3' => 'pages#events3'
  get 'news' => 'pages#news'
  get 'cs' => 'pages#cs'
  get 'leadership' => 'pages#leadership'
  get 'eventdesign' => 'pages#eventdesign'
  get 'brand' => 'pages#brand'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def brand
  end

  def contact
  end

  def cs
  end

  def events
  end

  def news
  end

  def partners
  end

  def services
  end

  def eventdesign
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <p> Stay Connected with <%= link_to "3PMedia Partners", "http://twitter.com/3pmediapartners" %> &nbsp; Site created by <%= link_to "Rails for Startups", "http://www.railsforstartups.com" %> </p>
  </small>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-custom" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
     <a class="navbar-brand" href="/"><center><img src="/images/3p.png"></a></center>
  </div>
    <ul class="nav pull-right">
      <li><a href="http://www.instagram.com/3pmediapartners" target="_blank"> <img src = "images/instagram-black.png"></a></li></ul>
      <ul class="nav pull-right">
      <li><a href="http://www.twitter.com/3pmediapartners" target="_blank"> <img src = "images/twitter-black.png"></a></li> </ul>
      <ul class="nav pull-right">
      <li><a href="http://www.facebook.com/3pmediapartners" target="_blank"> <img src = "images/facebook-black.png"></a></li></ul>
</nav>


<nav class="navbar navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
     

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
        <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">About Us <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="about">Company Profile</a></li>
                  <li><a href="leadership">Leadership Team</a></li>
                </ul>
              </li><!-- dropdown --> 
      <li><%= link_to "Our Partners", partners_path %></li> 
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="cs">Corporate Sponsorship</a></li>
                  <li><a href="eventdesign">Event Design & Planning</a></li>
                  <li><a href="brand">Brand Management</a></li>
                </ul>
              </li><!-- dropdown -->
 <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Events <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="events1">Pink Dolphin Promo</a></li>
                  <li><a href="events2">Music Meets Couture *Purchase Online*</a></li>
                  <li><a href="events3">After Party </a></li>
                </ul>
              </li><!-- dropdown -->
<li><%= link_to "Contact Us", contact_path %></li> 

  </div><!--/.nav-collapse -->


        </div><!-- /.container -->

      </div><!-- /.navbar-inner -->

    </div><!-- /.navbar -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Media</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>

	<div class="container">

    	<%= yield %>
		<%= render 'layouts/footer' %>

	</div>

</body>
</html>

app/views/pages/about.html.erb
<p align="justify"> <font size="4">
3P Media Partners is a multimedia agency built to integrate entertainment, sports and pop culture’ as we know it.  We specialize in brand management, executive event planning and corporate sponsorship. 
</font> </p>

<p align="justify"><font size="4"> Our business model affords scalability and flexibility, integrating strategic brand management with both advertisers and marketing conduits.  With nearly 30 years of experiences in product management & marketing, event planning, brand development and endorsements; we’re supremely confident that 3P Media Partners can shape your brand awareness and strategically align your products with your present and future consumers. 
</font></p>

<p align="justify"><font size="4"> 3P Media Partners will provide its clients marketing medium by which a product or services can be showcased to any audience of its choice.  We’re a results-driven firm that thrives on merging sports, entertainment and fashion through various conduits in a seamless manner.  Through our international network, we hope to expand our client’s network and reach exponentially.  We extremely confident that our suite of services will add immediate value all of our clients.
</font></p>
 
<p align="justify"><font size="4"> Our executive leadership team is committed to immeasurable client satisfaction and constant innovation.  Our common tie is the understanding how to leverage technology to drive awareness and brand recognition.  In addition, we’re fueled by a dynamic group of strategic partners throughout US and Europe. 
</font></p>
 
 
<center><p><font size="4"> ‘Integrity…..Commitment.....Perseverance’ </font></p></center>
 

app/views/pages/brand.html.erb
<p align="justify"><font size="4"> Brand Management. Our seasoned team of strategic consulting experts will work with you to design and/or identify and analyze opportunities in both the corporate and consumer marketplace. We’re committed to helping our clients capture and truly leverage the passion and unparalleled excitement of sports, entrainment and pop culture, translating into tangible business results.
 </font> </p>
&nbsp;
&nbsp;

<p><font size="4"> <b> * Marketing and Design </b> </font> </p>
<p><font size="4"> <b> *Endorsement Consultation </b> </font> </p>
<p><font size="4"> <b> *Career Transitioning </b> </font> </p>
<p><font size="4"> <b> *Social Responsibility </b> </font> </p>
<p><font size="4"> <b> *Crisis Management </b> </font> </p>

app/views/pages/contact.html.erb
<div class="jumbotron">
<p><h2><center> Our NYC Location: </h2></center>
<p><center><h3>

126 19th St
Ste 1 
NY, NY 11232 </p>
&nbsp;
&nbsp;
<p> Email: <a herf="mailto:info@3pmediapartners.com"> info@3pmediapartners.com </a> </p>

<p> Office:  (800) 449-1573 
Fax: (212) 409-8689 </h3> </p></center>
</h3>
</center>
</p>
</h2>
</p>
<center>
<a href="https://twitter.com/3pmediapartners" class="btn btn-twitter" data-show-count="false" data-size="large"><h3><center>Follow @3pmediapartners</center></h3> </a></h3> </center>	
</p>
</div>

app/views/pages/cs.html.erb
<p align="justify"><font size="4">

Corporate Sponsorship is one of the best ways for brands to engage directly with the public. 3P Media integrates sponsors into appropriate events to deliver key messaging to a targeted demographic. We service product launches, nightlife and venue promotions, as well as one-off opportunities such as celebrity and/or charity events. </P></font>

&nbsp;
&nbsp;
&nbsp;

<p align="justify"><font size="4"> <b> 3P MEDIA PARTNERS’ turnkey sponsorship services include: </font></P></b>

&nbsp;
&nbsp;

	<p> <font size="4"> * Competitive assessment </p> </font>

	<p> <font size="4"> * Sponsor evaluation </p> </font>
	
	<p> <font size="4"> * Contract negotiation </p> </font>

	<p> <font size="4"> * Strategic, creative and tactical program development </p> </font>
 
	<p> <font size="4"> * On-site management </p> </font>

	<p> <font size="4"> * Media production and distribution </p> </font>
 	
	<p> <font size="4"> * Corporate Consulting </p> </font>

	<p> <font size="4"> * Public Relations & Press Coverage </font> </p>

&nbsp;
&nbsp;
&nbsp;

<p align="justify"><font size="4"> We focus on providing tangible and measurable turnkey solutions for our clients.  Our success is a result of our commitment to the following core foundations of sponsorship creation: </P> </font>

<P> <font size="4"> <b> Forecast </P> </b> </font>

 <p align="justify"> <font size="4"> Assess each opportunity based on audience, reach and social metrics.  It’s essential that we quantify the potential value of sponsorships for clients.  This provides them a better mechanism to measure success and/or areas of optimization for said project initiatives.  </P> </font>
&nbsp;

<P> <font size="4"> <b> Track </P> </b> </font>

<p align="justify"><font size="4"> Automatically measure all social media, press, on-site engagements and total reach both pre and post the event.  Tracking the opinion and consideration lift generated by sponsorship in real-time provides a distinct advantage to our clients during the funding securitization process. </P> </font>

&nbsp;

<P> <font size="4"> <b> Optimize </P> </b> </font>

<p align="justify"><font size="4"> Routinely look to enhance sponsorship opportunities for our clients, leveraging technology and social media to create strong and repeatable process.  </P> </font>
&nbsp;
&nbsp;

app/views/pages/eventdesign.html.erb
<p align="justify"><font size="4">

Event Planning. From conception to completion, we specialized in event planning and design. Our team focuses on flawless execution, with attention to every detail ensuring a unique and memorable experience for our clients. Our past events include celebrity golf outings, charity galas, corporate engagements and both NFL and NBA sanctioned events just to name a few.

</font></P>

&nbsp;
&nbsp;

<P><font size="4"> <b> * Media & Public Relations </b> </font> </P>
 
<P><font size="4"> <b> * Event Planning & Execution </font> </P> </b>

<P><font size="4"><b> * Digital Strategy & Innovation </font> </P> </b>

<P><font size="4"><b>* Budget Creation & Management </b> </font> </P>

<P><font size="4"><b>* Vendor Procurement & Negotiation </b> </font> </P>

&nbsp;
&nbsp;

<p align="justify"><font size="4"> Offering the personal attention of a boutique company, 3P MEDIA PARTNERS leverages its relationships and contacts to create best-in-class events in the US and EU.   </font> </P>
&nbsp;
&nbsp;

<p align="justify"><font size="4"> These one-of-a-kind occasions are ideal for establishing brand awareness, gaining or renewing key business relationships and creating market-swell in multiple verticals.  </font> </P>

[Include some graphics to absorb some of the white space.]

app/views/pages/events1.html.erb
<center><img src = "images/event1.jpg"></center></a>

app/views/pages/events2.html.erb
<center><h1> <a href="http://www.eventbrite.com/e/7th-annual-where-music-meets-couture-showcase-tickets-7752944265"> Purchase your tickets online </center> </h1></a>
<center><a href="http://www.eventbrite.com/e/7th-annual-where-music-meets-couture-showcase-tickets-7752944265"><img src = "images/event2.jpg"></center></a>

app/views/pages/events3.html.erb
<center><img src = "images/event3.jpg"></center></a>

app/views/pages/home.html.erb
<html>
<head>
 
</head>
<body>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="/images/logohome.jpg" alt="">
      <div class="carousel-caption">
         <h3>Management | Marketing | PR | Branding</h3>
      </div>
    </div>
    <div class="item">
      <img src="/images/events.jpg" alt="">
      <div class="carousel-caption">
         <h3>Check out our latest events!</h3>
      </div>
     </div>
    <div class="item">
      <img src="/images/cs.jpg" alt="">
      <div class="carousel-caption">
         <h3>We can help with getting you Corporate Sponsorship</h3>
      </div>
     </div>
    <div class="item">
      <img src="/images/edp.jpg" alt="">
      <div class="carousel-caption">
         <h3>We do Event Design & Planning</h3>
      </div>
 </div>
<div class="item">
      <img src="/images/brandmanagemen.jpg" alt="">
      <div class="carousel-caption">
         <h3>Brand Management you can count on!</h3>
      </div>
 </div>
 </div>
  

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

    <!-- Example row of columns -->
    <div class="jumbotron">
      <div class="row">
        <div class="span4">
          <h3>Corporate Sponsorship</h3>
           <p>Corporate Sponsorship is one of the best ways for brands to engage directly with the public.  3P Media integrates sponsors into appropriate events to deliver key messaging to a targeted demographic.  </p>
          <p><a class="btn" href="cs">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h3>Event Design & Planning </h3>
           <p>Event Planning.  From conception to completion, we specialized in event planning and design.  We focus on flawless execution, with attention to every detail ensuring a unique and memorable experience for our clients.  </p>
          <p><a class="btn" href="eventdesign">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h3>Brand Management</h3>
          <p>Brand Management.  Our seasoned team of strategic consulting experts will work with you to design and/or identify and analyze opportunities in the sports marketplace.  </p>
          <p><a class="btn" href="brand">View details &raquo;</a></p>
        </div>
      </div>
</div>
  </body>
  </html>

app/views/pages/leadership.html.erb
<p><h4> <font color="#8C7853"> Jumoke S. Mendez, Managing Partner</h4></font>
<p><h4> <font color="#8C7853">Client Management and Relations </h4></font>
&nbsp;
<p align="justify"><font size="4"> 
Jumoke Mendez has worked in marketing and branding with some of the biggest names in sports and entertainment for over the past decade specializing in Branding and Private Client Services.  Jumoke graduated with his BA in Sports Management and Minor in Marketing from Florida International University in 2003.
</font></p>
&nbsp;
&nbsp;
<p align="justify"><font size="4"> 
Jumoke has worked on campaigns, for Hennessy Artistry Tour to Winter Music Conference, Ultra Music Festival, NBA Draft, NFL Draft and the VMA’s.  His 8 years of working heavily with corporate clients, celebrities, athletes, and brands landed him the incredible opportunity in 2011 to team up with mobile company  Mobli, a new startup platform for real-time visual media sharing based out of New York.  Joining Mobli he experienced extremely fast growth helping the company to aggressively increase their overall users and usage by utilizing his wealth of contacts and innovative marketing strategies.  His ideas, initiatives, resources, and aggregating content, helped play an intricate role bringing Mobli’s total funding to 88 Million during his time there.
</font></p>  
&nbsp;
&nbsp;
<p align="justify"><font size="4"> 
In 2013 Jumoke co-founded 3P Media Partners to mentor and guide young rising stars for both sports and entertainment. 3P allows talent to maximize their overall brand so each and every client reaches their true potential on and off the court, field, and stage.  Their goal is to educate, empower and manage their current/future clients so they succeed in every aspect of business which drives them to become global leaders and ambassadors which positions them to maximize their brand.   
</font></p>
&nbsp;
&nbsp;
<p><h4> <font color="#8C7853"> Earl D Silas, Jr, MBA, Managing Partner</h4></font>
<p><h4> <font color="#8C7853"> Corporate Strategy and Execution</h4></font>
&nbsp;
<p align="justify"><font size="4"> 
Earl has nearly 20 years in experience in both traditional corporate and entrepreneurial executive leadership.  Most known for his subtle demeanor and dynamic business prowess, the ‘man behind the curtain’ has been the driving force behind numerous projects since his early years in college.  Earl graduated Cum Laude w/ his MBA from Nova Southeastern and a proud alumnus of the University of Central Florida with a BA in Criminal Justice and Finance.
</font></p>
&nbsp;
&nbsp;
<p align="justify"><font size="4"> 
During his years as an entrepreneur on the entertainment side, Earl has worked with organizations such as BET, Source Magazine, Jazz in the Gardens, Nike Basketball Camp, South Beach Food and Wine Festival and the Orange Bowl Committee.  His past clients include both athletes and entertainers showcasing their talents during the ABFF, Hip Hop Awards, Zo’s Summer Groove and Nat Moore Florida Golf Classic to name a few.  
</font></p>
&nbsp;
&nbsp;
<p align="justify"><font size="4"> 
As a corporate professional, Earl has been instrumental in crafting the digital strategy for clients such as Home Depot, State Farm Insurance, Verizon, Tory Burch, Ralph Lauren and Tom Ford.  His experience has enabled his client to expand their digital footprint both in the US and Europe.   Currently, he’s the chief digital strategist for a boutique firm specializing in web design and eCommerce in Manhattan.  In additional to his role of a corporate executive, he’s one of the founding members of the Tap & Cork Series and 3P Media Partners.  
</font></p>
&nbsp;
&nbsp;
<p><h4> <font color="#8C7853"> Travis Bond</h4></font>
<p><h4> <font color="#8C7853"> Chief Social Media Architect</h4></font>
&nbsp;
<p align="justify"><font size="4"> 
Travis Bond is a social media strategist, trainer and speaker located in the Greater Los Angeles area that specializes in helping companies and clients better connect with its customers via social media. He has been actively immersed in social media since 2007, and in that time, has helped businesses of all shapes and sizes better connect with their customers via these amazing tools and sites. His clients include businesses of all sizes, from sole proprietorships, film stars to major Hollywood studios.  His goal is to help his clients create connections with their customers, and nurture them into relationships that help grow their bottom line.  
 </font></p>
&nbsp;
&nbsp;
<p align="justify"><font size="4"> 
Additionally, Travis’s thoughts and expertise on Marketing, Brand Advocacy and Social Media have been sought by some of the world’s most prestigious entertainers and Hollywood film studios such as Fox Searchlight. Some of Travis's most recent projects and clients include the major motion picture Baggage Claim, written and directed by David E. Talbert, La La Vasquez's The Love Playbook and the E! News anchor and film star Terrence J's Amazon's Best Selling book The Wealth of My Mothers Wisdom to name a few.
</font></p>
&nbsp;
&nbsp;
<p><h4> <font color="#8C7853"> John Fuller</h4></font>
<p><h4> <font color="#8C7853"> Corporate Publicist</h4></font>
&nbsp;
<p align="justify"><font size="4"> 
John Fuller worked as a public relations specialist for some of the top stars in sports over the past decade, and specializes in non-traditional sports publicity.  Independently, he represents current MLB National League Andrew McCutchen and UFC stars Benson Henderson and Carlos Condit. He has also provided public relations services in the past for former NFL stars Terrell Owens, LaVar Arrington, Bernard Berrian and Cato June, MLB All-Star Curtis Granderson, and UFC Champion Jon "Bones" Jones.
</font></p>
&nbsp;
&nbsp;
<p align="justify"><font size="4"> 
His clients have been featured on numerous talk shows, including Ellen, The View and Late Show with David Letterman and in various worldwide, national and regional publications.  Previously, he worked for five years under the U.S. Olympic Committee helping to provide exposure for numerous athletes within the sports world. Through the USOC and its international events, he provided support for sports including baseball, basketball, boxing, softball, swimming, tennis, wrestling and weightlifting, working with the biggest stars in those respective sports to ensure positive, quality publicity.
</font></p>
&nbsp;
<center><p><font size="4"> ‘Integrity…..Commitment.....Perseverance’ </font></p></center>
 

app/views/pages/news.html.erb
<h1>Pages#news</h1>
<p>Find me in app/views/pages/news.html.erb</p>

app/views/pages/partners.html.erb
<p align="justify"><font size="4">
3P Media Partners applies experience, professionalism and integrity as the core fundamentals of our success, past, present and future.  We’ve partnered with some of the world's most recognized brands, foundations and corporations for over the past 10 years.  Our engagements span from small networking events on South Beach to nationally marketed fundraisers off Wilshire Blvd in LA and all points in between.  Our goal is to routinely exceed our client  business goals and consumer reach, which can only be accomplished with dynamic partnerships.  A list of some of 3P Media’s past and present partners can be found below: </font></p>
&nbsp;
&nbsp;

&nbsp;
&nbsp;
		
&nbsp;
&nbsp;
<center>
<table border="1">
<tr>
<td><img src = "images/reebok.jpg"></td>
<td><img src = "images/union.jpg"></td>
<td><img src = "images/Adidas.jpg"></td>
<td><img src = "images/Inc.jpg"></td>
<td><img src = "images/Maserati.jpg"></td>
<td><img src = "images/Apple.jpg"></td>
<td><img src = "images/redbull.jpg"></td>
<td><img src = "images/heineken.jpg"></td>
<td><img src = "images/audi1.jpg"></td>
</tr>
<tr>
<td><img src = "images/1.jpg"></td>
<td><img src = "images/2.jpg"></td>
<td><img src = "images/3.jpg"></td>
<td><img src = "images/4.jpg"></td>
<td><img src = "images/5.jpg"></td>
<td><img src = "images/6.jpg"></td>
<td><img src = "images/7.jpg"></td>
<td><img src = "images/8.jpg"></td>
<td><img src = "images/sony1.jpg"></td>
</tr>
<tr><td><img src = "images/mtv.jpg"></td>
<td><img src = "images/9.jpg"></td>
<td><img src = "images/12.jpg"></td>
<td><img src = "images/13.jpg"></td>
<td><img src = "images/14.jpg"></td>
<td><img src = "images/15.jpg"></td>
<td><img src = "images/16.jpg"></td>
<td><img src = "images/18.jpg"></td>
<td><img src = "images/side1.jpg"></td>
</tr>
</table>
</center>

app/views/pages/services.html.erb
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>